### ISSUE TITLE
Compilation error on Windows

### ISSUE THREAD

**Issue by schungx** [rhaiscript/rhai-dylib#3]
https://github.com/rhaiscript/rhai-dylib/blob/main/src/plugin_loader/dylib.rs#L61 needs to be replaced by a feature gate, as `if cfg!(...)` will also try to compile the block (only to have it discarded via `if false`).

**Comment by ltabis** [comment]
Should be fixed with https://github.com/rhaiscript/rhai-dylib/commit/396309f67e2b36019fc5085c3086cf31d1d58463
