### ISSUE TITLE
Use compile_error to prevent building unless under linux or windows.

### ISSUE THREAD

**Issue by schungx** [rhaiscript/rhai-dylib#5]
In `lib.rs` consider adding a line:

```rust
#[cfg(not(target_os = "linux"))]
#[cfg(not(target_os = "windows"))]
compile_error!("unsupported platform - only Linux & Windows are supported");
```

This way the crate won't build on o/s other than Linux and Windows.

**Comment by ltabis** [comment]
Done in d4f0e9db3650c060068ed6ef3fdf6a4a3e47b0f7

**Comment by schungx** [comment]
Actually you only need one `compile_error` in `lib.rs` as the compilation cannot go on. You don't need iy anywhere else.
