### ISSUE TITLE
Warning ModuleResolver::resolve_raw signature changes

### ISSUE THREAD

**Issue by schungx** [rhaiscript/rhai-dylib#7]
I have made modifications to the `ModuleResolver::resolve_raw` method to take an additional `&mut Scope` parameter.

The change is currently in my fork, so I want to give you a heads-up just so you'd know what's coming.

**Comment by ltabis** [comment]
Updqted here https://github.com/rhaiscript/rhai-dylib/commit/a7a94b82b23f9b26175d8e1937a09b3cc8917366 ;)
