### ISSUE TITLE
TypeId info to add to the README

### ISSUE THREAD

**Issue by fabriziosestito** [rhaiscript/rhai-dylib#9]
After struggling a bit with  TypeIds mismatch, I was able to compile two crates with the same TypeIds.
I briefly followed this StackOverflow answer: https://stackoverflow.com/questions/57536484/consistent-typeids-for-dynamically-loaded-crates

In particular I had to:
- set the same ahash seed
- use the same toolchain version for all crates
- use the same rhai-dylib dependency version in all crates
- disable link time optimization flag (-C lto) in one of the two crates
- both crates need to be built with the same target type (both debug or both release)

Maybe those info could be added to the README in the Pitfalls section

**Comment by schungx** [comment]
Not so sure about the LTO and debug/release...  I suppose @ltabis can shed some light?

I remember LTO turned on working fine, so @fabriziosestito  can you check?

**Comment by ltabis** [comment]
@fabriziosestito I've added your potential solutions [here](https://github.com/rhaiscript/rhai-dylib#others), thanks a lot !
